services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: production
    container_name: backend_app
    restart: unless-stopped
    ports:
      - ${API_PORT}:3000
    env_file:
      - .env
    working_dir: /usr/src/app
    networks:
      - backend_app_network

networks:
  backend_app_network:
